name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "* * * * *" # See https://crontab.guru/#5/5_0-23_*_*_*

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "sthadiwash@gmail.com"
          git config --local user.name "Diwas"
          git add -A
          
          arr[0]="commit-god(bot): 😂 auto commit"
          arr[1]="commit-god(bot): 😱 auto commit"
          arr[2]="commit-god(bot): 👿 auto commit"
          arr[3]="commit-god(bot): 💩 auto commit"
          arr[4]="commit-god(bot): 🙏 auto commit"
          arr[5]="commit-god(bot): 🙈 auto commit"
          arr[6]="commit-god(bot): 🐐 auto commit"
          arr[7]="commit-god(bot): 🤖 auto commit"
          arr[8]="commit-god(bot): 🟩 auto commit"
          arr[9]="commit-god(bot): 👻 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
